### ISSUE TITLE
A11Y Audit

### ISSUE THREAD

**Issue by alebarbaja** [urlint/www#1]
Hello, I did an accessibility audit and I found some errors. After the adjustments, the audit increased to 100%. Do you want the changes to increase or is it not necessary?.

After:
<img width="944" alt="captura de pantalla 2018-05-18 a las 12 59 54" src="https://user-images.githubusercontent.com/28918805/40231586-f5ac0d0c-5a9b-11e8-9cc8-9b33aa35e4cd.png">

Before:
<img width="946" alt="captura de pantalla 2018-05-18 a las 12 59 16" src="https://user-images.githubusercontent.com/28918805/40231596-ffede736-5a9b-11e8-9b05-6c33a972a3e1.png">

**Comment by Kikobeats** [comment]
I don't understand. is this related with urlint? is the target url of the test urlint.co? 🤔

**Comment by alebarbaja** [comment]
Yes, indeed

**Comment by Kikobeats** [comment]
Then yes, can you make the PR to merge the changes? 🙂
